server:
  isa-global-config-path: /usr/local/app/pcmgr_bigdata/isa_global.ini
  raw-event-topic: raw_event


yunjing-kafka:
  topics: event_msg,fast_msg,host_login,bash_scan,asset_account,asset_port,asset_process
  consumer-group: cg_soc_yunjing #Kafka consumer group definition
  offset-oldest: false #Kafka consumer consume initial offset from oldest
  version: 2.1.1 #Kafka cluster version
  assignor: range #Consumer group partition assignment strategy (range, roundrobin)
  brokers: 127.0.0.1:9092

log:
  name: yjtosocserver # Logger的名字
  development: true # 是否是开发模式。如果是开发模式，会对DPanicLevel进行堆栈跟踪。
  level: debug # 日志级别，优先级从低到高依次为：debug, info, warn, error, dpanic, panic, fatal。
  format: console # 支持的日志输出格式，目前支持console和json两种。console其实就是text格式。
  enable-color: true # 是否开启颜色输出，true:是，false:否
  disable-caller: false # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件、函数和行号
  disable-stacktrace: false # 是否再panic及以上级别禁止打印堆栈信息
  output-paths: /Users/gavinlhchenlh/test/yjtosocserver.log,stdout # 支持输出到多个输出，逗号分开。支持输出到标准输出（stdout）和文件。
  error-output-paths: /Users/gavinlhchenlh/test/yjtosocserver.error.log # zap内部(非业务)错误日志输出路径，多个输出，逗号分开