package yunjingconvert

import (
	"github.com/gavinlhchen/logconvert/app"
	"github.com/gavinlhchen/logconvert/internal/yunjingconvert/config"
	"github.com/gavinlhchen/logconvert/internal/yunjingconvert/options"
	"github.com/gavinlhchen/logconvert/log"
)

const commandDesc = `The Yunjing Convert Server get alert and host log generated by yunjing from yunjing's kafka,
parse from protobuf to plain text, then send to soc's  kafka`

func NewApp(basename string) *app.App {
	opts := options.NewOptions()
	application := app.NewApp("Yunjing Convert",
		basename,
		app.WithOptions(opts),
		app.WithDescription(commandDesc),
		app.WithDefaultValidArgs(),
		app.WithRunFunc(run(opts)),
	)

	return application
}

func run(opts *options.Options) app.RunFunc {
	return func(basename string) error {
		log.Init(opts.Log)
		defer log.Flush()

		cfg, err := config.CreateConfigFromOptions(opts)
		if err != nil {
			return err
		}

		return Run(cfg)
	}

}
